# Default configuration for RSNA Trauma Detection model
# All paths will be converted to Path objects automatically

# Required parameters (must be provided via command line or config file)
output_dir: null  # Path to save model and results
data_dir: null    # Path to the dataset directory
csv_path: null    # Path to the CSV file containing class ID to name mapping

train_csv: "train.csv"  # Path to the specific split CSV file
valid_csv: "valid.csv"
test_csv: "valid.csv"   # Using validation set as test set (test set labels hidden)

# Dataset parameters
dataset:
  dataset_name: chexpert
  mask_dir: null                  # Optional: Path to directory containing masks
  selected_classes: null          # List of class names to use (others treated as background)
  num_workers: 0                  # Number of data loading workers
  fraction: 1.0                   # Train/validation split ratio
  image_size: 512                 # Input image size
  num_classes: 2                  # Number of target classes

# Model parameters
model:
  batch_size: 32                  # Input batch size for training
  resume: null                    # Resume full model and optimizer state from checkpoint
  pretrained: true                # Use pretrained model

# Optimizer parameters
optimizer:
  weight_decay: 0.01              # Weight decay factor

# Learning rate schedule parameters
lr_scheduler:
  epochs: 8                       # Number of epochs to train
  learning_rate: 1.0e-3           # Learning rate for the optimizer
  warmup_ratio: 0.1               # Ratio of warmup steps
  patience: 7                     # Early stopping patience

# Device & distributed training parameters
device:
  amp: "no"                       # Automatic mixed precision: "no", "fp16", "bf16"
  device: "cuda:0"                # Device to use: "cpu", "cuda:0", etc.

# Logging parameters
logging:
  logger: "tensorboard"           # Logger to use: "tensorboard", "neptune", "clearml"
  
  # Neptune logger parameters (only required if logger="neptune")
  neptune:
    project: null                 # Neptune project name
    api_token: null               # Neptune API token
    run_id: null                  # Neptune run ID to resume (e.g., "CLS-123")
  
  # ClearML logger parameters (only required if logger="clearml")
  clearml:
    project: null                 # ClearML project name
    task_id: false                # ClearML task ID to resume or boolean flag
    task_type: "training"         # ClearML task type
    tags: []                      # List of tags for ClearML task
  
  experiment_name: null           # Name for the experiment

# Miscellaneous parameters
misc:
  seed: 42                        # Random seed
  validation_freq: 100            # Frequency of validation (iterations)
  log_freq: 100                   # Frequency of logging metrics (iterations)
  save_freq: 100                  # Frequency of saving checkpoints (iterations)

transforms:  
  random_crop:
    crop_size: 224
  # random_horizontal_flip: 0.5
  # random_affine: null
  # color_jitter: null
  # norm: norm
