# Sample user configuration for RSNA Trauma Detection model
# Override only the values you wish to change from default_config.yaml

# Required paths - must be specified
output_dir: "./outputs/experiment1"
data_dir: "./data/rsna_dataset"
csv_path: "./data/class_mapping.csv"

# Dataset customization
dataset:
  image_size: 768                 # Increased from default 512
  selected_classes: ["hemorrhage", "fracture"]  # Focus on specific injuries

# Model parameters
model:
  batch_size: 16                  # Reduced batch size for higher resolution
  pretrained: true

# Training parameters
lr_scheduler:
  epochs: 15                      # Extended training time
  learning_rate: 5.0e-4           # Custom learning rate
  patience: 10                    # Increased patience for early stopping

# Device configuration
device:
  amp: "fp16"                     # Enable mixed precision
  device: "cuda:0"                # Use specific GPU

# Logging configuration
logging:
  logger: "neptune"
  experiment_name: "rsna_trauma_detection_exp1"
  neptune:
    project: "username/rsna-project"

# Random seed for reproducibility
misc:
  seed: 123